var modules =
[
    [ "LED Board Support API", "group__led__bsp.html", "group__led__bsp" ],
    [ "MX25 SPI Multi-I/O Flash Memory Driver", "group__mx25__driver.html", "group__mx25__driver" ],
    [ "Push button driver board support", "group__pushbutton__evkit.html", "group__pushbutton__evkit" ],
    [ "Analog To Digital Converter (ADC)", "group__adc.html", "group__adc" ],
    [ "Trust Protection Unit", "group__tpu.html", "group__tpu" ],
    [ "Direct Memory Access (DMA)", "group__dma.html", "group__dma" ],
    [ "External Memory Cache Controller (EMCC)", "group__emcc.html", "group__emcc" ],
    [ "Flash Controller  (FLC)", "group__flc.html", "group__flc" ],
    [ "General-Purpose Input/Output (GPIO)", "group__gpio.html", "group__gpio" ],
    [ "HTMR", "group__htmr.html", "group__htmr" ],
    [ "I2C", "group__i2c.html", "group__i2c" ],
    [ "ICC_Registers", "group__icc__registers.html", "group__icc__registers" ],
    [ "Low Power (Power Sequencer)", "group__pwrseq.html", "group__pwrseq" ],
    [ "1-Wire Master (OWM)", "group__owm.html", "group__owm" ],
    [ "Pulse Train Engine (PT)", "group__pt.html", "group__pt" ],
    [ "Resource Protection Unit", "group__rpu.html", "group__rpu" ],
    [ "RTC", "group__rtc.html", "group__rtc" ],
    [ "Secure Digital High Capacity (SDHC)", "group__sdhc.html", "group__sdhc" ],
    [ "Semaphore (SEMA)", "group__sema.html", "group__sema" ],
    [ "SPI", "group__spi.html", "group__spi" ],
    [ "SPI External Flash (SPIXF)", "group__spixf.html", "group__spixf" ],
    [ "SPI External Flash Controller (SPIXFC)", "group__spixfc.html", "group__spixfc" ],
    [ "SPI External Ram (SPIXR)", "group__spixr.html", "group__spixr" ],
    [ "Timer (TMR)", "group__tmr.html", "group__tmr" ],
    [ "TRNG_Registers", "group__trng__registers.html", "group__trng__registers" ],
    [ "UART", "group__uart.html", "group__uart" ],
    [ "Watchdog Timer (WDT)", "group__wdt.html", "group__wdt" ],
    [ "Error Codes", "group__MXC__Error__Codes.html", "group__MXC__Error__Codes" ],
    [ "Exclusive Access Locks", "group__mxc__lock__utilities.html", "group__mxc__lock__utilities" ],
    [ "Delay Utility Functions", "group__MXC__delay.html", "group__MXC__delay" ],
    [ "Assertion Checks for Debugging", "group__mxc__assertions.html", "group__mxc__assertions" ]
];