var group___g_a_t_t___p_r_o_f_i_l_e_s =
[
    [ "Alert Notification Profile", "group___a_l_e_r_t___n_o_t_i_f_i_c_a_t_i_o_n___p_r_o_f_i_l_e.html", "group___a_l_e_r_t___n_o_t_i_f_i_c_a_t_i_o_n___p_r_o_f_i_l_e" ],
    [ "Battery Profile", "group___b_a_t_t_e_r_y___p_r_o_f_i_l_e.html", "group___b_a_t_t_e_r_y___p_r_o_f_i_l_e" ],
    [ "Blood Pressure Profile", "group___b_l_o_o_d___p_r_e_s_s_u_r_e___p_r_o_f_i_l_e.html", "group___b_l_o_o_d___p_r_e_s_s_u_r_e___p_r_o_f_i_l_e" ],
    [ "Cycling Power Profile", "group___c_y_c_l_i_n_g___p_o_w_e_r___p_r_o_f_i_l_e.html", "group___c_y_c_l_i_n_g___p_o_w_e_r___p_r_o_f_i_l_e" ],
    [ "Cycling Speed And Cadence Profile", "group___c_y_c_l_i_n_g___s_p_e_e_d___a_n_d___c_a_d_e_n_c_e___p_r_o_f_i_l_e.html", "group___c_y_c_l_i_n_g___s_p_e_e_d___a_n_d___c_a_d_e_n_c_e___p_r_o_f_i_l_e" ],
    [ "Device Information Profile", "group___d_e_v_i_c_e___i_n_f_o_r_m_a_t_i_o_n___p_r_o_f_i_l_e.html", "group___d_e_v_i_c_e___i_n_f_o_r_m_a_t_i_o_n___p_r_o_f_i_l_e" ],
    [ "Find Me Profile", "group___f_i_n_d___m_e___p_r_o_f_i_l_e.html", "group___f_i_n_d___m_e___p_r_o_f_i_l_e" ],
    [ "Gap Profile", "group___g_a_p___p_r_o_f_i_l_e.html", "group___g_a_p___p_r_o_f_i_l_e" ],
    [ "Gatt Profile", "group___g_a_t_t___p_r_o_f_i_l_e.html", "group___g_a_t_t___p_r_o_f_i_l_e" ],
    [ "Glucose Profile", "group___g_l_u_c_o_s_e___p_r_o_f_i_l_e.html", "group___g_l_u_c_o_s_e___p_r_o_f_i_l_e" ],
    [ "Human Interface Device Profile", "group___h_u_m_a_n___i_n_t_e_r_f_a_c_e___d_e_v_i_c_e___p_r_o_f_i_l_e.html", "group___h_u_m_a_n___i_n_t_e_r_f_a_c_e___d_e_v_i_c_e___p_r_o_f_i_l_e" ],
    [ "Heart Rate Profile", "group___h_e_a_r_t___r_a_t_e___p_r_o_f_i_l_e.html", "group___h_e_a_r_t___r_a_t_e___p_r_o_f_i_l_e" ],
    [ "Health Thermometer Profile", "group___h_e_a_l_t_h___t_h_e_r_m_o_m_e_t_e_r___p_r_o_f_i_l_e.html", "group___h_e_a_l_t_h___t_h_e_r_m_o_m_e_t_e_r___p_r_o_f_i_l_e" ],
    [ "Phone Alert Status Profile", "group___p_h_o_n_e___a_l_e_r_t___s_t_a_t_u_s___p_r_o_f_i_l_e.html", "group___p_h_o_n_e___a_l_e_r_t___s_t_a_t_u_s___p_r_o_f_i_l_e" ],
    [ "Pulse Oximeter Profile", "group___p_u_l_s_e___o_x_i_m_e_t_e_r___p_r_o_f_i_l_e.html", "group___p_u_l_s_e___o_x_i_m_e_t_e_r___p_r_o_f_i_l_e" ],
    [ "Running Speed And Cadence Profile", "group___r_u_n_n_i_n_g___s_p_e_e_d___a_n_d___c_a_d_e_n_c_e___p_r_o_f_i_l_e.html", "group___r_u_n_n_i_n_g___s_p_e_e_d___a_n_d___c_a_d_e_n_c_e___p_r_o_f_i_l_e" ],
    [ "Scan Parameter Profile", "group___s_c_a_n___p_a_r_a_m_e_t_e_r___p_r_o_f_i_l_e.html", "group___s_c_a_n___p_a_r_a_m_e_t_e_r___p_r_o_f_i_l_e" ],
    [ "Gyroscope Service Profile", "group___g_y_r_o_s_c_o_p_e___s_e_r_v_i_c_e___p_r_o_f_i_l_e.html", "group___g_y_r_o_s_c_o_p_e___s_e_r_v_i_c_e___p_r_o_f_i_l_e" ],
    [ "Temperature Service Profile", "group___t_e_m_p_e_r_a_t_u_r_e___s_e_r_v_i_c_e___p_r_o_f_i_l_e.html", "group___t_e_m_p_e_r_a_t_u_r_e___s_e_r_v_i_c_e___p_r_o_f_i_l_e" ],
    [ "Time Profile", "group___t_i_m_e___p_r_o_f_i_l_e.html", "group___t_i_m_e___p_r_o_f_i_l_e" ],
    [ "User Data Profile", "group___u_s_e_r___d_a_t_a___p_r_o_f_i_l_e.html", "group___u_s_e_r___d_a_t_a___p_r_o_f_i_l_e" ],
    [ "Uribeacon Configuration Profile", "group___u_r_i_b_e_a_c_o_n___c_o_n_f_i_g_u_r_a_t_i_o_n___p_r_o_f_i_l_e.html", "group___u_r_i_b_e_a_c_o_n___c_o_n_f_i_g_u_r_a_t_i_o_n___p_r_o_f_i_l_e" ],
    [ "Wireless Data Exchange Profile", "group___w_i_r_e_l_e_s_s___d_a_t_a___e_x_c_h_a_n_g_e___p_r_o_f_i_l_e.html", "group___w_i_r_e_l_e_s_s___d_a_t_a___e_x_c_h_a_n_g_e___p_r_o_f_i_l_e" ],
    [ "Arm Ltd Proprietary Profile", "group___a_r_m___l_t_d___p_r_o_p_r_i_e_t_a_r_y___p_r_o_f_i_l_e.html", "group___a_r_m___l_t_d___p_r_o_p_r_i_e_t_a_r_y___p_r_o_f_i_l_e" ],
    [ "Weight Scale Profile", "group___w_e_i_g_h_t___s_c_a_l_e___p_r_o_f_i_l_e.html", "group___w_e_i_g_h_t___s_c_a_l_e___p_r_o_f_i_l_e" ],
    [ "Alert-Related Service", "group___a_l_e_r_t-_r_e_l_a_t_e_d___s_e_r_v_i_c_e.html", "group___a_l_e_r_t-_r_e_l_a_t_e_d___s_e_r_v_i_c_e" ],
    [ "Battery Service", "group___b_a_t_t_e_r_y___s_e_r_v_i_c_e.html", "group___b_a_t_t_e_r_y___s_e_r_v_i_c_e" ],
    [ "Blood Pressure Service", "group___b_l_o_o_d___p_r_e_s_s_u_r_e___s_e_r_v_i_c_e.html", "group___b_l_o_o_d___p_r_e_s_s_u_r_e___s_e_r_v_i_c_e" ],
    [ "Service Configuration", "group___s_e_r_v_i_c_e___c_o_n_f_i_g_u_r_a_t_i_o_n.html", "group___s_e_r_v_i_c_e___c_o_n_f_i_g_u_r_a_t_i_o_n" ],
    [ "Service Constants", "group___s_e_r_v_i_c_e___c_o_n_s_t_a_n_t_s.html", "group___s_e_r_v_i_c_e___c_o_n_s_t_a_n_t_s" ],
    [ "Gatt And Gap Service", "group___g_a_t_t___a_n_d___g_a_p___s_e_r_v_i_c_e.html", "group___g_a_t_t___a_n_d___g_a_p___s_e_r_v_i_c_e" ],
    [ "Cycling Power Service", "group___c_y_c_l_i_n_g___p_o_w_e_r___s_e_r_v_i_c_e.html", "group___c_y_c_l_i_n_g___p_o_w_e_r___s_e_r_v_i_c_e" ],
    [ "Cycling Speed And Cadence Service", "group___c_y_c_l_i_n_g___s_p_e_e_d___a_n_d___c_a_d_e_n_c_e___s_e_r_v_i_c_e.html", "group___c_y_c_l_i_n_g___s_p_e_e_d___a_n_d___c_a_d_e_n_c_e___s_e_r_v_i_c_e" ],
    [ "Device Information Service", "group___d_e_v_i_c_e___i_n_f_o_r_m_a_t_i_o_n___s_e_r_v_i_c_e.html", "group___d_e_v_i_c_e___i_n_f_o_r_m_a_t_i_o_n___s_e_r_v_i_c_e" ],
    [ "Glucose Service", "group___g_l_u_c_o_s_e___s_e_r_v_i_c_e.html", "group___g_l_u_c_o_s_e___s_e_r_v_i_c_e" ],
    [ "Gyroscope Sensor Service", "group___g_y_r_o_s_c_o_p_e___s_e_n_s_o_r___s_e_r_v_i_c_e.html", "group___g_y_r_o_s_c_o_p_e___s_e_n_s_o_r___s_e_r_v_i_c_e" ],
    [ "Human Interface Device Service", "group___h_u_m_a_n___i_n_t_e_r_f_a_c_e___d_e_v_i_c_e___s_e_r_v_i_c_e.html", "group___h_u_m_a_n___i_n_t_e_r_f_a_c_e___d_e_v_i_c_e___s_e_r_v_i_c_e" ],
    [ "Heart Rate Service", "group___h_e_a_r_t___r_a_t_e___s_e_r_v_i_c_e.html", "group___h_e_a_r_t___r_a_t_e___s_e_r_v_i_c_e" ],
    [ "Health Thermometer Service", "group___h_e_a_l_t_h___t_h_e_r_m_o_m_e_t_e_r___s_e_r_v_i_c_e.html", "group___h_e_a_l_t_h___t_h_e_r_m_o_m_e_t_e_r___s_e_r_v_i_c_e" ],
    [ "Internet Profile Support Service", "group___i_n_t_e_r_n_e_t___p_r_o_f_i_l_e___s_u_p_p_o_r_t___s_e_r_v_i_c_e.html", "group___i_n_t_e_r_n_e_t___p_r_o_f_i_l_e___s_u_p_p_o_r_t___s_e_r_v_i_c_e" ],
    [ "Pulse Oximiter Service", "group___p_u_l_s_e___o_x_i_m_i_t_e_r___s_e_r_v_i_c_e.html", "group___p_u_l_s_e___o_x_i_m_i_t_e_r___s_e_r_v_i_c_e" ],
    [ "Proximity Service", "group___p_r_o_x_i_m_i_t_y___s_e_r_v_i_c_e.html", "group___p_r_o_x_i_m_i_t_y___s_e_r_v_i_c_e" ],
    [ "Running Speed And Cadence Service", "group___r_u_n_n_i_n_g___s_p_e_e_d___a_n_d___c_a_d_e_n_c_e___s_e_r_v_i_c_e.html", "group___r_u_n_n_i_n_g___s_p_e_e_d___a_n_d___c_a_d_e_n_c_e___s_e_r_v_i_c_e" ],
    [ "Scan Parameter Service", "group___s_c_a_n___p_a_r_a_m_e_t_e_r___s_e_r_v_i_c_e.html", "group___s_c_a_n___p_a_r_a_m_e_t_e_r___s_e_r_v_i_c_e" ],
    [ "Temperature Sensor Service", "group___t_e_m_p_e_r_a_t_u_r_e___s_e_n_s_o_r___s_e_r_v_i_c_e.html", "group___t_e_m_p_e_r_a_t_u_r_e___s_e_n_s_o_r___s_e_r_v_i_c_e" ],
    [ "Time-Related Service", "group___t_i_m_e-_r_e_l_a_t_e_d___s_e_r_v_i_c_e.html", "group___t_i_m_e-_r_e_l_a_t_e_d___s_e_r_v_i_c_e" ],
    [ "Uricfg Configuration Service", "group___u_r_i_c_f_g___c_o_n_f_i_g_u_r_a_t_i_o_n___s_e_r_v_i_c_e.html", "group___u_r_i_c_f_g___c_o_n_f_i_g_u_r_a_t_i_o_n___s_e_r_v_i_c_e" ],
    [ "Wireless Data Exchange Service", "group___w_i_r_e_l_e_s_s___d_a_t_a___e_x_c_h_a_n_g_e___s_e_r_v_i_c_e.html", "group___w_i_r_e_l_e_s_s___d_a_t_a___e_x_c_h_a_n_g_e___s_e_r_v_i_c_e" ],
    [ "Wp Service", "group___w_p___s_e_r_v_i_c_e.html", "group___w_p___s_e_r_v_i_c_e" ],
    [ "Weight Scale Service", "group___w_e_i_g_h_t___s_c_a_l_e___s_e_r_v_i_c_e.html", "group___w_e_i_g_h_t___s_c_a_l_e___s_e_r_v_i_c_e" ]
];